const EXERCISE_ACTIVE = 'EXERCISE_ACTIVE';
const EXERCISE_PAUSE = 'EXERCISE_PAUSE';
const EXERCISE_REST = 'EXERCISE_REST';

const NOT_SET = 'NOT_SET';

const BEGINNER_LEVEL = 'BEGINNER_LEVEL';
const INTERMEDIATE_LEVEL = 'INTERMEDIATE_LEVEL';
const ADVANCED_LEVEL = 'ADVANCED_LEVEL';
const EXPERT_LEVEL = 'EXPERT_LEVEL';

export {
  EXERCISE_ACTIVE,
  EXERCISE_PAUSE,
  EXERCISE_REST,
  NOT_SET,
  BEGINNER_LEVEL,
  INTERMEDIATE_LEVEL,
  ADVANCED_LEVEL,
  EXPERT_LEVEL,
};
