const EXERCISE_ACTIVE = 'EXERCISE_ACTIVE';
const EXERCISE_PAUSE = 'EXERCISE_PAUSE';
const EXERCISE_REST = 'EXERCISE_REST';
const EXERCISE_COMPLETE = 'EXERCISE_COMPLETE';
const EXERCISE_ABORT = 'EXERCISE_ABORT';

const ENABLE_SOUND = 'ENABLE_SOUND';
const DISABLE_SOUND = 'DISABLE_SOUND';

const NOT_SET = 'NOT_SET';

const BEGINNER_LEVEL = 'BEGINNER_LEVEL';
const INTERMEDIATE_LEVEL = 'INTERMEDIATE_LEVEL';
const ADVANCED_LEVEL = 'ADVANCED_LEVEL';
const EXPERT_LEVEL = 'EXPERT_LEVEL';

const NOT_SET_SOUND = 'NOT_SET_SOUND';
const PERFORM_PUSH_UP_SOUND = 'PERFORM_PUSH_UP_SOUND';
const REST_SOUND = 'REST_SOUND';
const EXERCISE_COMPLETE_SOUND = 'EXERCISE_COMPLETE_SOUND';
const BEEP_SOUND = 'BEEP_SOUND';

const PROGRAM_ACTIVE = 'PROGRAM_ACTIVE';
const PROGRAM_COMPLETE = 'PROGRAM_COMPLETE';

const NOTIFICATION_ENABLED = 'NOTIFICATION_ENABLED';
const NOTIFICATION_DISABLED = 'NOTIFICATION_DISABLED';

const SOUND_ENABLED = 'SOUND_ENABLED';
const SOUND_DISABLED = 'SOUND_DISABLED';

const PRO_ENABLED = 'PRO_ENABLED';
const PRO_DISABLED = 'PRO_DISABLED';

const PRO_PROGRAM = 'PRO_PROGRAM';
const FREE_PROGRAM = 'FREE_PROGRAM';

export {
  EXERCISE_ACTIVE,
  EXERCISE_PAUSE,
  EXERCISE_REST,
  EXERCISE_COMPLETE,
  EXERCISE_ABORT,
  ENABLE_SOUND,
  DISABLE_SOUND,
  NOT_SET,
  BEGINNER_LEVEL,
  INTERMEDIATE_LEVEL,
  ADVANCED_LEVEL,
  EXPERT_LEVEL,
  NOT_SET_SOUND,
  PERFORM_PUSH_UP_SOUND,
  REST_SOUND,
  EXERCISE_COMPLETE_SOUND,
  BEEP_SOUND,
  PROGRAM_ACTIVE,
  PROGRAM_COMPLETE,
  NOTIFICATION_ENABLED,
  NOTIFICATION_DISABLED,
  SOUND_ENABLED,
  SOUND_DISABLED,
  PRO_ENABLED,
  PRO_DISABLED,
  PRO_PROGRAM,
  FREE_PROGRAM,
};
