const EXERCISE_ACTIVE = 'EXERCISE_ACTIVE';
const EXERCISE_PAUSE = 'EXERCISE_PAUSE';
const EXERCISE_REST = 'EXERCISE_REST';
const EXERCISE_COMPLETE = 'EXERCISE_COMPLETE';

const NOT_SET = 'NOT_SET';

const BEGINNER_LEVEL = 'BEGINNER_LEVEL';
const INTERMEDIATE_LEVEL = 'INTERMEDIATE_LEVEL';
const ADVANCED_LEVEL = 'ADVANCED_LEVEL';
const EXPERT_LEVEL = 'EXPERT_LEVEL';

const NOT_SET_SOUND = 'NOT_SET_SOUND';
const PERFORM_PUSH_UP_SOUND = 'PERFORM_PUSH_UP_SOUND';
const REST_SOUND = 'REST_SOUND';
const EXERCISE_COMPLETE_SOUND = 'EXERCISE_COMPLETE_SOUND';
const BEEP_SOUND = 'BEEP_SOUND';

export {
  EXERCISE_ACTIVE,
  EXERCISE_PAUSE,
  EXERCISE_REST,
  EXERCISE_COMPLETE,
  NOT_SET,
  BEGINNER_LEVEL,
  INTERMEDIATE_LEVEL,
  ADVANCED_LEVEL,
  EXPERT_LEVEL,
  NOT_SET_SOUND,
  PERFORM_PUSH_UP_SOUND,
  REST_SOUND,
  EXERCISE_COMPLETE_SOUND,
  BEEP_SOUND,
};
