// Navigation
export const SET_TAB = 'SET_TAB';

export const NAVIGATION_FORWARD = 'NAVIGATION_FORWARD';
export const NAVIGATION_BACK = 'NAVIGATION_BACK';
export const NAVIGATION_RESET = 'NAVIGATION_RESET';

export const NAVIGATION_TOGGLE_ICON = 'NAVIGATION_TOGGLE_ICON';

// Programs (exercises)
export const PROGRAM_SET_EXERCISE = 'PROGRAM_SET_EXERCISE';

// Async
export const PROGRAM_SAVE_ATTEMPT = 'PROGRAM_SAVE_ATTEMPT';
export const PROGRAM_SAVE_SUCCESS = 'PROGRAM_SAVE_SUCCESS';
export const PROGRAM_SAVE_FAILURE = 'PROGRAM_SAVE_FAILURE';

export const PROGRAM_GET_FETCH = 'PROGRAM_GET_FETCH';
export const PROGRAM_GET_SUCCESS = 'PROGRAM_GET_SUCCESS';
export const PROGRAM_GET_FAILURE = 'PROGRAM_GET_FAILURE';

export const PROGRAM_REMOVE_SELECTED_ATTEMPT = 'PROGRAM_REMOVE_SELECTED_ATTEMPT';
export const PROGRAM_REMOVE_SELECTED_SUCCESS = 'PROGRAM_REMOVE_SELECTED_SUCCESS';
export const PROGRAM_REMOVE_SELECTED_FAILURE = 'PROGRAM_REMOVE_SELECTED_FAILURE';

export const PROGRAM_SET_PREVIEW_EXERCISE = 'PROGRAM_SET_PREVIEW_EXERCISE';

export const PROGRAM_DAY_COMPLETE = 'PROGRAM_DAY_COMPLETE';

export const PROGRAM_GET_EXERCISE_BY_NAME = 'PROGRAM_GET_EXERCISE_BY_NAME';

export const PROGRAM_RESET = 'PROGRAM_RESET';

// Statistics
export const STATISTICS_SET = 'STATISTICS_SET';

// Async
export const STATISTICS_SAVE_ATTEMPT = 'STATISTICS_SAVE_ATTEMPT';
export const STATISTICS_SAVE_SUCCESS = 'STATISTICS_SAVE_SUCCESS';
export const STATISTICS_SAVE_FAILURE = 'STATISTICS_SAVE_FAILURE';

export const STATISTICS_GET_SUCCESS = 'STATISTICS_GET_SUCCESS';
export const STATISTICS_GET_FAILURE = 'STATISTICS_GET_FAILURE';
export const STATISTICS_GET_FETCH = 'STATISTICS_GET_FETCH';

export const STATISTICS_REMOVE_ATTEMPT = 'STATISTICS_REMOVE_ATTEMPT';
export const STATISTICS_REMOVE_SUCCESS = 'STATISTICS_REMOVE_SUCCESS';
export const STATISTICS_REMOVE_FAILURE = 'STATISTICS_REMOVE_FAILURE';

// Exercise

// Async
export const EXERCISE_SAVE_ATTEMPT = 'EXERCISE_SAVE_ATTEMPT';
export const EXERCISE_SAVE_SUCCESS = 'EXERCISE_SAVE_SUCCESS';
export const EXERCISE_SAVE_FAILURE = 'EXERCISE_SAVE_FAILURE';

export const EXERCISE_GET_SUCCESS = 'EXERCISE_GET_SUCCESS';
export const EXERCISE_GET_FAILURE = 'EXERCISE_GET_FAILURE';
export const EXERCISE_GET_FETCH = 'EXERCISE_GET_FETCH';

export const EXERCISE_REMOVE_ATTEMPT = 'EXERCISE_REMOVE_ATTEMPT';
export const EXERCISE_REMOVE_SUCCESS = 'EXERCISE_REMOVE_SUCCESS';
export const EXERCISE_REMOVE_FAILURE = 'EXERCISE_REMOVE_FAILURE';

export const EXERCISE_SET_SETS = 'EXERCISE_SET_SETS';
export const EXERCISE_SET_REP = 'EXERCISE_SET_REP';
export const EXERCISE_NEXT_SET = 'EXERCISE_NEXT_SET';
export const EXERCISE_INCREMENT_REP = 'EXERCISE_INCREMENT_REP';
export const EXERCISE_DECREMENT_REP = 'EXERCISE_DECREMENT_REP';
export const EXERCISE_SET_MODE = 'EXERCISE_SET_MODE';
export const EXERCISE_ABORT = 'EXERCISE_ABORT';

export const EXERCISE_SET_DEC_INTERVAL_ID = 'EXERCISE_SET_DEC_INTERVAL_ID';
export const EXERCISE_CLEAR_DEC_INTERVAL_ID = 'EXERCISE_CLEAR_DEC_INTERVAL_ID';
export const EXERCISE_DECREASE_TIMER = 'EXERCISE_DECREASE_TIMER';

export const EXERCISE_SET_TIME_ELAPSED_INTERVAL_ID = 'EXERCISE_SET_TIME_ELAPSED_INTERVAL_ID';
export const EXERCISE_CLEAR_TIME_ELAPSED_INTERVAL_ID = 'EXERCISE_CLEAR_TIME_ELAPSED_INTERVAL_ID';
export const EXERCISE_ELAPSED_TIME_INCREASE = 'EXERCISE_ELAPSED_TIME_INCREASE';

export const EXERCISE_RESET = 'EXERCISE_RESET';

export const EXERCISE_TOGGLE_SOUND = 'EXERCISE_TOGGLE_SOUND';

// Complete
export const COMPLETE_SET = 'COMPLETE_SET';
export const COMPLETE_RESET = 'COMPLETE_RESET';
