// Navigation
export const SET_TAB = 'SET_TAB';

export const NAVIGATION_FORWARD = 'NAVIGATION_FORWARD';
export const NAVIGATION_BACK = 'NAVIGATION_BACK';

// Programs (exercises)
export const PROGRAM_SAVE = 'PROGRAM_SAVE';
export const PROGRAM_GET_NAME_SUCCESS = 'PROGRAM_GET_NAME_SUCCESS';
export const PROGRAM_GET_NAME_FAILURE = 'PROGRAM_GET_NAME_FAILURE';
export const PROGRAM_GET_NAME_FETCH = 'PROGRAM_GET_NAME_FETCH';
