// Navigation
export const SET_TAB = 'SET_TAB';

export const NAVIGATION_FORWARD = 'NAVIGATION_FORWARD';
export const NAVIGATION_BACK = 'NAVIGATION_BACK';

// Programs (exercises)
export const PROGRAM_SAVE_NAME_SUCCESS = 'PROGRAM_SAVE_NAME_SUCCESS';
export const PROGRAM_SAVE_NAME_FAILURE = 'PROGRAM_SAVE_NAME_FAILURE';

export const PROGRAM_GET_SUCCESS = 'PROGRAM_GET_SUCCESS';
export const PROGRAM_GET_FAILURE = 'PROGRAM_GET_FAILURE';
export const PROGRAM_GET_FETCH = 'PROGRAM_GET_FETCH';

export const PROGRAM_REMOVE_SELECTED_SUCCESS = 'PROGRAM_REMOVE_SELECTED_SUCCESS';
export const PROGRAM_REMOVE_SELECTED_FAILURE = 'PROGRAM_REMOVE_SELECTED_FAILURE';

// Statistics
export const STATISTICS_GET_SUCCESS = 'STATISTICS_GET_SUCCESS';
export const STATISTICS_GET_FAILURE = 'STATISTICS_GET_FAILURE';
export const STATISTICS_GET_FETCH = 'STATISTICS_GET_FETCH';

export const STATISTICS_REMOVE_SUCCESS = 'STATISTICS_REMOVE_SUCCESS';
export const STATISTICS_REMOVE_FAILURE = 'STATISTICS_REMOVE_FAILURE';
