const COLOR_ORANGE = '#C9A643';
const COLOR_RED = '#B20000';

const LINE_COLOR = '#E6E6E6';
const TAB_COLOR = '#302D30';
const FADE_COLOR = '#333333';

const BASE_BACKGROUND_COLOR = '#F6F6F6';
const BASE_PADDING_LEFT = 20;
const BASE_PADDING_RIGHT = 20;
const BASE_FONT_FAMILY_IOS = 'Helvetica-Light';

const ACTIVITY_BACKGROUND_COLOR = 'rgb(48, 45, 48)';

const ICON_SIZE = 30;

export {
  COLOR_ORANGE,
  COLOR_RED,
  LINE_COLOR,
  TAB_COLOR,
  FADE_COLOR,
  BASE_BACKGROUND_COLOR,
  BASE_PADDING_LEFT,
  BASE_PADDING_RIGHT,
  BASE_FONT_FAMILY_IOS,
  ACTIVITY_BACKGROUND_COLOR,
  ICON_SIZE,
};
