# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'PushUps' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PushUps
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'SwiftyJSON', git: 'https://github.com/IBM-Swift/SwiftyJSON.git'
  pod 'Charts', git: 'https://github.com/consenlabs/Charts.git', branch: ‘Swift-3.0’

  target 'PushUpsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
